name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo Installing Node 16...
            curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
            sudo apt install -y nodejs
            sudo apt install -y npm
            cd /var/www/html/github-actions-ec2-demo
            git remote set-url origin git@github.com:abednahouli/github-actions-ec2-demo-v1.git
            sudo git pull
            npm ci
            npm run build
